### ISSUE TITLE
Telemetry prefs

### ISSUE THREAD

**Issue by 51114u9** [schomery/privacy-settings#22]
Yesterday published ["How to disable the Firefox Saved Telemetry Pings and archive folder"](http://www.ghacks.net/2015/11/09/how-to-disable-the-firefox-saved-telemetry-pings-and-archive-folder/) . 

In this article, Martin suggests to stop the generation of telemetry pings and archived pings change this options:

* `toolkit.telemetry.archive.enabled=false`
* `toolkit.telemetry.enabled=false`
* `toolkit.telemetry.unified=false`

The preference `toolkit.telemetry.unified` finally controls unified behavior. Do we add these other options or we moved to this new option?

**Comment by berrythesoftwarecodeprogrammar** [comment]
i think `enabled` and `unified` might both need to be `false`
https://github.com/pyllyukko/user.js/issues/63

**Comment by inbasic** [comment]
Thanks for the report. Both prefs are now available on [0.1.8b1](https://github.com/schomery/privacy-settings/blob/master/src/executables/extension.xpi?raw=true)

**Comment by geokis** [comment]
Can someone explain why the **[Heartbeat](https://wiki.mozilla.org/Advocacy/heartbeat)** setting is not in the telemtry section? 

`browser.selfsupport.url` string `https://self-repair.mozilla.org/%LOCALE%/repair`

**Comment by schomery** [comment]
@geokis isn't `toolkit.telemetry.enabled=false` enough to prevent heartbeat prompts?

**Comment by geokis** [comment]
I am not quite sure... personally I have never seen this survey on the desktop version of firefox.
I could find nothing about it on Google, only the information, to disable Heartbeat the **string** value mast be **empty**.

Since I use PrivacySettings I have disabled the telemetry stats, but for some weeks I have all the telemetry stats active, because I want to support Mozilla with some some feedback. But no survey display.

Maybe someone has more information about Heartbeat.
