### ISSUE TITLE
Reduce spacing in popover

### ISSUE THREAD

**Issue by franco999** [schomery/privacy-settings#56]
It should reduce excessive spacing that exists in the popover
![ps](https://cloud.githubusercontent.com/assets/12088580/16737717/fda8b570-4768-11e6-9b2a-88aaa03077fc.png)

**Comment by Gitoffthelawn** [comment]
I think the spacing you are seeing is due to overflow from the strings being wider than their object boxes and not truncating or wrapping.

**Comment by schomery** [comment]
@franco999 is your default zoom level to 100%? I can add truncation to CSS, but since the extension calculates the width and height, there should not be an overlapping issue.

Would you please try the latest dev and let me know if you see the same issue here or not?
[0.2.3b1.xpi.zip](https://github.com/schomery/privacy-settings/files/434537/0.2.3b1.xpi.zip)

**Comment by franco999** [comment]
In Firefox for Android, it happens the same as on the PC.
I'll try the version dev see what happens.

![ps](https://cloud.githubusercontent.com/assets/12088580/17951283/620a256c-6a37-11e6-824b-0cf53560edf7.png)

**Comment by schomery** [comment]
The new push should have fixed this bug. Please give it a try

**Comment by schomery** [comment]
https://github.com/schomery/privacy-settings/blob/master/builds/0.2.3b3.xpi?raw=true

**Comment by franco999** [comment]
@schomery  With v0.2.3b3 in desktop and font size 12. Fixed, thanks.
![ps](https://cloud.githubusercontent.com/assets/12088580/17973158/b61a5ff2-6ab7-11e6-945e-2714ff842b95.png)

**Comment by schomery** [comment]
Great! Thanks for the report.
