### ISSUE TITLE
Performance impact

### ISSUE THREAD

**Issue by Gitoffthelawn** [schomery/privacy-settings#60]
Firefox's `about:performance` is reporting an impact on framerate due to this extension.  Except when this extension's panel is open, there should not be any performance impact.

**Comment by schomery** [comment]
Well, for the panel, it only gets constructed when user requests it. Meaning that there is no hidden panel; https://github.com/schomery/privacy-settings/blob/master/src/lib/desktop.js#L75-L79

The only impact this extension might have is due to an observer for the advanced window. 
https://github.com/schomery/privacy-settings/blob/master/src/lib/main.js#L238-L251

I have even removed observers on prefs. Basically the extension does nothing when the panel is hidden (rather than having an observer for the advanced window). The framerate issue is already reported to https://groups.google.com/forum/#!topic/mozilla-labs-jetpack/ZTIFn6wffS4
Doesn't seem like that we can do anything or maybe I am missing something. Please review the code and let me know if you have any suggestions to improve the performance. To me the extension should not have any impact on Firefox except when the panel is open.

**Comment by Gitoffthelawn** [comment]
> To me the extension should not have any impact on Firefox except when the panel is open.

:+1: 

So there must be a bug in `about:performance` or the extension.

**Comment by schomery** [comment]
The new WebExtension version should not have any performance impact on tabs.
https://github.com/schomery/privacy-settings/issues/80

**Comment by Gitoffthelawn** [comment]
Great!  Thank you! 😃
